### ISSUE TITLE
Price split is not shown correctly when multiple coupons are applied

### ISSUE THREAD

**Issue by ashika123** [ajency/Foodstree#27]
Steps:
1.Apply multiple  coupons in a order.(Logged in as frodo)
2.Login as admin and click on orders.
3.Open the order.
Current Behaviour: The discount split for the coupons is not shown correctly
Expected Behaviour: The discount split for the coupons has to be shown correctly.
![couponcalc](https://cloud.githubusercontent.com/assets/9797052/5609457/08636b1e-94c7-11e4-85fa-547ecf358335.png)

**Comment by robiulpro** [comment]
In coupon edit screen, there is an option 'Apply before tax'. If this option is enabled, discount amount calculation will be applied in product level, because in ecommerce, tax calculation is always product level. In this case the coupon will be applied before calculating the tax  (if any) for each item. So this is the scenario:

'IF APPLY BEFORE TAX' IS CHECKED

SCENARIO 1
IF the discount amount is a fixed amount
THEN discount amount will be equally divided into each item, based on item's price ratio and same will be deducted, also the final amount will be shown below the actual amount 

SCENARIO 2
IF the discount amount is PERCENTAGE
THEN discount amount will be calculated for each item based on item's price and discount percentage. Same will be deducted for each item and the final amount will be shown below the actual amount.


For above screenshot, the first coupon goes to scenario 1.  Rs. 100 flat discount was divided into two items in ratio, (respectively 47.92 and 52.08). And for second coupon, 20% discount applied for cart amount (960-100 = 860).
